# Generated by Django 3.1.7 on 2021-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='link',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
