# Generated by Django 3.1.7 on 2021-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aliment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
