# Generated by Django 3.2 on 2021-05-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_aliment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='home.category'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='al_score', to='home.aliment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
